### ISSUE TITLE
Weapons collide with walls when firing from the upper shadowy areas

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#1]
When you stand at the top near the upper shadows, weapons don't fire because they are i...

**Comment by richtaur** [comment]
This is particularly problematic with the new demoblin's behavior of running from you: you can get him stuck up against the top wall and all his projectiles disappear.

**Comment by geoffb** [comment]
Reduced bounding box of projectiles which causes them not to collide with the walls immediately upon being fired near walls. Closed by 6d33210b16bce10d3a65119838729b354ee5163f
