### ISSUE TITLE
Weapons should kill each other the way walls kill them

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#100]
When a weapon hits a wall, it does the cool death animation where it spins and fades out. Can we do that when weapons hit each other? Would look awesome when an arrow or trident is coming at you and you shoot with with your knives or some shit.

**Comment by geoffb** [comment]
Revamped damage routines. Physical weapons now deflect. Added a new stat called 'piercing' which affects whether or not a project can pass through objects it kills in one hit. Closed by 08ffdf3b4db79eb5873bb0a8f684c24f93a85845 and Closed by 08ffdf3b4db79eb5873bb0a8f684c24f93a85845
