### ISSUE TITLE
Bosses flashing red for pain

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#104]
In an ideal world, we'd have this feature. Dunno if we'll ever get it in or not but thought I'd make an issue anyway. The red overlay on the current sprites is:

`rgba(186, 51, 35, 0.6)`

**Comment by geoffb** [comment]
It would be nice. However, outside of crazy slow per pixel canvas manipulation I'm not sure how to achieve it. :(

**Comment by richtaur** [comment]
closed by 7575135220acee776e7270b30eea303ecbdefd29

**Comment by richtaur** [comment]
You just got served.

**Comment by geoffb** [comment]
Hot damn! Nice work!!

You have snatched the pebble...
