### ISSUE TITLE
Save game state and allow user to continue

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#108]
We need to save the following to local storage:

Player:
- Wounds
- Weapons
- Gold
- Kills and other stats

Game:
- Current Wave ID
- ???

We need to add a "Continue" option to the title screen which is disabled if there isn't a save game.

The player's game will auto save after each boss (waves 10, 20, 30 and 40).

**Comment by geoffb** [comment]
Save game code complete! 232985c2d397d8767dc9dd1cab707a96c58b52b0

I updated the title screen so that "How to Play" is currently "Continue"

Kicking this over to Matt for title screen updates:
- Change "Play!" to "New Game"
- Add "Continue" below "Play!"
- Color the "Continue" option gray or something if the local storage var "checkpoint_wave" is null. (The code already won't allow the user to select continue if there's no data, we just need a visual indication of this)

**Comment by richtaur** [comment]
Yay, this is in!
