### ISSUE TITLE
Audit sounds

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#110]
Go through all the sounds and list any missing/redundant sounds here. Every enemy, etc. should have its own unique sounds!

**Comment by geoffb** [comment]
Enemies without sound effects:
- Flaming Skull
- Owlbear
- Gel (use Cube sounds?)
- Wizard (currently using goblin sounds)
- Sandworm
- Nega Xam
- Beholder Eyelet

**Comment by richtaur** [comment]
Put some in ... not complete yet tho.

**Comment by richtaur** [comment]
Went through everything, here's where we're at:
- owl bear doesn't make a sound when he attacks
- demoblin is using some goblin sounds
- wizard is using some goblin sounds
- need negaxam
- need beholder

**Comment by richtaur** [comment]
Feedback is that the imp dying sound is unpleasant and possibly confusing.

**Comment by richtaur** [comment]
- Axe bouncing off wall should make a sound.

**Comment by richtaur** [comment]
closed by 418e90451fd252ada63b24e00cf747319b6ea8dc finished audit -- will open a new issue for the sounds we need
