### ISSUE TITLE
Set the high score

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#112]
This is an essential step that I want to make sure we don't forget about. The default high score to beat right now makes no sense and essentially can't be beaten.

Just a one-line change but a pretty important one :)

**Comment by geoffb** [comment]
I'm thinking we should set the default stupid low so that you're basically guaranteed to set your own record if you beat even one wave.

**Comment by richtaur** [comment]
closed by 598ea60edf5aae2087e1f54ece3afed34c738786 you're totally right i was overthinking that. even one kill is worthy of rewarding the player
