### ISSUE TITLE
All enemies should stop knives

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#113]
Right now bats don't.

**Comment by geoffb** [comment]
Revamped damage routines. Physical weapons now deflect. Added a new stat called 'piercing' which affects whether or not a project can pass through objects it kills in one hit. closed by 08ffdf3b4db79eb5873bb0a8f684c24f93a85845 and closed by 08ffdf3b4db79eb5873bb0a8f684c24f93a85845
