### ISSUE TITLE
Can destroy all enemy projectiles now

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#117]
Including:
- Cyclops
- Superclops
- Wizard
- Dragon

**Comment by geoffb** [comment]
Boss projectiles cannot be destroyed again. Closed by aac9b55d926e362ca05bcb3e0ed22e29cb91e238

**Comment by richtaur** [comment]
Now the indestructible projectiles make bat noises! :D

**Comment by geoffb** [comment]
Fixed by 3cc5656990ed65ebd9e85fd3ed18cd03a977e035.
