### ISSUE TITLE
Boss names

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#120]
To give our game more personality and to enable conversation to more easily happen, we should name our bosses. They are:
- Superclops
- Green Dragon
- Gelatinous Cube
- Beholder
- Nega Xam

We'll have to play with it to see what works best, eg "Boss: Superclops!" or what.

**Comment by geoffb** [comment]
Boss names announced via wave text. Closed by 2e1c2c5b6f461d9ab1b09ad6078b1e7bbcde64fe
