### ISSUE TITLE
Doom key codes

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#123]
- ldkfa = weapons
- lddqd = god mode
- ldclev# = warp to wave #
- lddebug = toggle debug mode

**Comment by richtaur** [comment]
- ldstat = show a modal with your current stats (accuracy, score, etc.)

**Comment by geoffb** [comment]
Doom key codes. Closed by 4b85be1c55889e8e761ba6dec82adf3075991ea7

**Comment by geoffb** [comment]
Didn't implement ldclev# cause it's not as straight forward and not necessary for launch.
