### ISSUE TITLE
Visual polish

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#127]
Ideas so far:
- Make 3 different gate graphics with defects.
- Medieval flags hanging between gates.
- Spiderwebs in the corner.

**Comment by richtaur** [comment]
- Finish the armor on the demoblins.

**Comment by geoffb** [comment]
Add some muck to the bottom of the walls, perhaps.

**Comment by richtaur** [comment]
When you pick up gold, the dollar signs look confusing. Tweak them somehow!

**Comment by richtaur** [comment]
Change superclops. He looks like he's poisoned.

**Comment by richtaur** [comment]
Change the meat behind the leftmost gate to something else that is not in the game (eg, skulls or dirt).

**Comment by richtaur** [comment]
Make the first bats bluish. Make the dire bats more reddish brown.

**Comment by richtaur** [comment]
Implement new sandworm that Jon helped with and give dirt a higher contrast.

**Comment by richtaur** [comment]
Make superclops more like a demon-clops. Satyr?

**Comment by richtaur** [comment]
Add a new graphic for the dragon to use for his blue fire. Make it a higher contrast with the green, so maybe purple?

**Comment by richtaur** [comment]
Make wizard projectiles purple (like their bodies) and more shockwave-like.

**Comment by geoffb** [comment]
Stop scaling up text anywhere; it looks like ass on Windows.

**Comment by geoffb** [comment]
Make beholder eyelets less "stop sign".

**Comment by geoffb** [comment]
In addition to removing the text scaling start using the "Cracked" font where it looks good.

**Comment by richtaur** [comment]
closed by 52279c756037474fabcf3cb735a36dd54f1c8766 (and made new issues out of the rest of the comments)
