### ISSUE TITLE
HTML5 Caching

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#130]
Use `localStorage` or something to cache shit so users don't have to wait after the first load and we don't have to keep spending money on bandwidth. Yay!

**Comment by geoffb** [comment]
We should also include a cache manifest for all the sound and images.

**Comment by richtaur** [comment]
See 1b562c82b42afc0a11d1d1c58fda56950a6b143e. I got `cache.manifest` in there, and everything works … on the first page load. Following page loads throw this error:

`Failed to load resource: The URL can’t be shown` for various files.
No idea! Guess I'll try again later.

**Comment by richtaur** [comment]
Fuck this.
