### ISSUE TITLE
Superclops disappears

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#131]
Sometime Superclops will "disappear". He can still be heard firing rocks so he must be outside the walls somehow. Could be related to the new charge mechanic.

**Comment by richtaur** [comment]
Note: cube disappears too!

**Comment by richtaur** [comment]
Another note: when I quit the game, he reappeared. Just commenting in case it's useful somehow.

**Comment by geoffb** [comment]
Small, but fundemental change to collision detection which _should_ eliminate the crazy warping outside the walls bugs for good. Closed by 753bc76a7d7ad2aa5c22a2d7acbeba253b50888b
