### ISSUE TITLE
Arrows sometimes move incredibly slowly

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#14]
This will be really hard to duplicate but thought it would be worth mentioning anyway: sometimes I've noticed arrows moving really slowly across the screen, like as slow as 1px/second.

I've only ever seen it happen to arrows and only after playing quite a few waves.

**Comment by geoffb** [comment]
I actually know why this happens, heh.

I've got some random direction code that generates directions that are <1 for both X and Y which results in slow projects as the speed of the object is multiplied by it's direction. (and in the case of <1 makes the object move "slower")

**Comment by geoffb** [comment]
Fixed random direction generation. Closed by 6b0420f2d1ebed068197b849782ce7214b8440eb
