### ISSUE TITLE
High Score Issues

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#142]
- Doesn't seem to send consistently. Looks to be caused by the placement inside the stat drawing code. I'd recommend pulling it out of there and into .endGame()
- The score calculation should be as follows: Waves _completed_ x 1000. So, if you are on wave 3 and you die, you should get 2 x 1000 points. Only if you beat Doppelganger should you get 50 x 1000 points.

The calculation for wave points should look something like this:

```
// This will be the wave the player died on (or wave 50 if he beat the game)
var currentWave = (this.currentWaveId + 1); // WaveId is zero based

if (!this.wonGame) {
    // Player has not won the game meaning they died on the current wave
    var wavesComplete = (currentWave - 1);
} else {
    // Player beat the game; give them credit for all 50 waves
    var wavesComplete = currentWave;
}

var wavePoints = (wavesComplete * 1000);
```

**Comment by richtaur** [comment]
closed by 7cf6d6b2a52b3224ee7cf3d9869b2cdecca6ba7f
