### ISSUE TITLE
No enemies on screen for long periods of time

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#158]
Try Wave 24 with Fire Sword and kill the clops quickly. The player ends up just sitting there waiting for the next round of enemies and it feels broken. (same with Owl Bears, wave 26).

I think a good fix woud be: next round of enemies automatically triggered when there are no enemies in the arena.

**Comment by geoffb** [comment]
The only trigger for next wave should be the game detecting that there are zero enemies in the arena. (We removed the time based wave roll over because it was wildly unpopular.)

I take a look at why this isn't working on the waves in question though.

**Comment by geoffb** [comment]
Oooooooh, I just got this. You mean that the delay between monsters in the same wave should be removed if there are no monsters in the arena.

**Comment by geoffb** [comment]
Fixed by f9626c8f49b25cfd5c7a17a17234598e5f6fd74c.
