### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#163]
Get them into the game. Might need to change some things because we want the demo on `lostdecadegamesapp.appspot.com` (which we have GA running on) as well as the given `play.lostdecadegames.com` analytics.

**Comment by geoffb** [comment]
So, the current build has GA for `play.lostdecadegames.com` and is tracking. I dunno what to do about `lostdecadegamesapp.appspot.com`. I think we should just redirect it and be done with it.

**Comment by richtaur** [comment]
Sounds good. We'll do that once we're ready to go live with v1.

**Comment by richtaur** [comment]
Use #178 for the last bit.
