### ISSUE TITLE
Onslaught Arena Production Web Setup

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#168]
Here's what I'd like to see:

**/onslaught_arena**

Serves full or demo version of the game depending on if the google user has bought the game or not; forces google auth. Demo does not record high scores to the global list.

**/onslaught_arena/demo**

Always the demo. No forced sign in. Demo does not record high scores to the global list. `lostdecadegamesapp.appspot.com` redirects here.

**/onslaught_arena/high_scores**

High scores, duh.

**Comment by richtaur** [comment]
FUCK YEAH!
