### ISSUE TITLE
"Native size" toggle

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#179]
We need a subtle button that will toggle off/on the resizing behavior. (Scaling up is a pretty big performance hit) It'd be great to be able to toggle this behavior without having to resize the browser window.

I'm thinking something semi transparent that looks similar to:
http://tanjero.com/bitplayer/images/fullscreen.gif

We can overlay it in the top left or right corner of the game, perhaps.

**Comment by geoffb** [comment]
Functional with placeholder icon: 2e08db69aed2782d18bbf283b9dee74d81247fd6

Just need a couple of icons for enable/disable fullscreen.

**Comment by richtaur** [comment]
closed by 3b2e0e8fcb464394ee6d52f941901d9852e519b7
