### ISSUE TITLE
Beholder firesword drop

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#185]
> When I defeat a boss, if I don't grab the loot it drops quickly enough, the game will go "Game Saved!" and it will save my state from before grabbing the loot.  For the beholder boss, this means that loading my game puts me on level 41 without the fire sword, and I die very quickly.

To solve this:
- Put a high TTL on firesword and don't move to the next wave until it's picked up.
- Make a bouncing arrow icon to message to the user that they must pick it up.

**Comment by geoffb** [comment]
Fire sword now forced upon the player before they can continue to wave 41. Closed by 2e4aa079e955c6b5ae12089874377ca8ef71894b
