### ISSUE TITLE
Improved obfuscation

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#188]
Basically we want to make the code as difficult as possible to fuck with.

**Comment by richtaur** [comment]
Let's kick the version up to `1.1.x` when we push this to production since it's a pretty major change.

**Comment by geoffb** [comment]
Marking this as "LATER" because we don't want to introduce such drastic changes this close to launch.

**Comment by richtaur** [comment]
Closing! It's already out there anyway :D
