### ISSUE TITLE
Doppelganger improvements

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#189]
He feels great but his biggest problem right now is that he's a bit too random. It can feel like he requires more luck than skill sometimes and that's not what we want. Some ideas on how to improve him:
- Don't let the safeSpots in spike_walls be within maybe 3 spikes of doppelganger
  (player is guaranteed to get hit when they appear just below and/or to the right of him)
- Running around randomly throwing axes, maybe he can move in a pattern instead? Also if he targeted you instead of throwing random directions that could create more skill over luck.
- Ditto for running around dropping spikes (would also look more attractive if they appeared on the grid instead of sometimes mushed together)

**Comment by geoffb** [comment]
Doppelganger behavior improvements. Closed by d19272fe8526521e8a29c5de9b80241ed6f7cb97
