### ISSUE TITLE
Christmas Theme!

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#202]
Let's do some simple Christmas theming for a sale during the week of Christmas.

Here's what I'm thinking:
- Snow on the arena ground and walls. Maybe Christmas lights around the gates?
- Santa hat for Xam
- Reindeer antlers and red nose for goblins or cyclops
- Turn some projectile into a snowball?

We don't have to do all of these. I think the first two would be fine.

**Comment by richtaur** [comment]
Xmas is passed! D'oh. Maybe next year :P
