### ISSUE TITLE
Ice weapon

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#213]
Need these assets:
- Weapon itself (maybe an icicle)
- 16x16 "frozen" graphic to overlay enemies
- 32x32 of the same

Might be neat if it had a subtle frost trail (could use the current blue flame maybe)

**Comment by geoffb** [comment]
For the trail we should whip up a light blue with sparkles kind of effect. Two frames should be fine. Semi transparent.

**Comment by richtaur** [comment]
cf2637e1702af75f63792ebab99bc1580aa70c18
Ice images and sound effect. Mostly placeholders, I'll make them look more betterer once they're in-game.

**Comment by richtaur** [comment]
It's in, closing. We're mostly using gc-onslaught nowadays anyway.
