### ISSUE TITLE
New enemy: Beholder boss

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#24]
BEHOLD!!

Should have eye stalks which are separate enemies that have TBD behavior.

**Comment by geoffb** [comment]
Nixed.

**Comment by richtaur** [comment]
Reopened, lez do it.

**Comment by richtaur** [comment]
- Should feel fucking epic.
- Make him drool!
- Thin up the tentacles and have them wiggle.
- Make some little floating buddies: gross eyeballs.
- Maybe you can't damage him until all his satellite eyes are dead?

**Comment by richtaur** [comment]
- Maybe at 75% etc. he floats up into the air and some shit flies out of the gates or something.
- Maybe he has green gas clouds or something that fuck up the hero's controls.

**Comment by geoffb** [comment]
- Enters from the sky
- Eye is closed, spawns adds
- Adds circle around beholder, eye opens
- Takes damage now that eye is open
- Eye closes after a while, becomes invincible again
- Vomits gas clouds
- Spawns adds, rinse, repeat

At 50% the beholder shoots a spread fire of energy balls during eye open phase.

**Comment by richtaur** [comment]
This is done I just need to piece it together into a new sprite sheet.

Did we decide to do the eyeballs/retinas separately so they can track the player or should we just do it simple and have it behave like a regular sprite?

We're probably already going to want the shadow to be rendered separately since there's stuff like it will appear first as the beholder lowers etc.

**Comment by geoffb** [comment]
I'd say let's do the eye as part of the beholder; no player tracking etc. It's just easier that way and we can get cranking on mew + Onslaught Tactics ASAP :)

**Comment by richtaur** [comment]
Totally. Beholder assets in b03e72ce973c8aeeccd970c2f5731066b6e71af5. We'll talk about which animations to combine (like eye closed+mouth opened, etc.)

**Comment by richtaur** [comment]
Almost ready!! Will be solid after tonight.
