### ISSUE TITLE
Pause when window loses focus

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#26]
Might be good to show a screen like "click here to play" if the window ever needs focus, like even from the title screen.

**Comment by geoffb** [comment]
If it's easy...

**Comment by richtaur** [comment]
closed by 3364cfd93fc9407e2eee2c491872bd4f99150a79, pausing when window loses focus

**Comment by richtaur** [comment]
Fixed by: 3364cfd93fc9407e2eee
