### ISSUE TITLE
Obfuscate the code

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#34]
Otherwise if we're like "hey we will open source it at 1,000 sales!" people will be like "or I can just view source, you douches."

**Comment by richtaur** [comment]
Try wrapping it all in an anonymous function to trigger ALL variables as private.

**Comment by geoffb** [comment]
Experiment with not calling object methods as variables or string literals. (e.g. object[foo] or object['foo']

**Comment by geoffb** [comment]
Seems like using the advanced optimizations of Closure complier aren't going to work for us without some major investigation/refactoring. It's good enough for now for this game since this codebase is dead.
