### ISSUE TITLE
Sometimes enemies get stuck in the upper/left corner

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#41]
Seen it several times, mostly bats and goblins. Could be the reason the gates stop opening sometimes.

**Comment by richtaur** [comment]
This happened to a wizard, too. He disappeared but I can still hear his sound effect once in a while. Nothing else happening on the screen!

**Comment by geoffb** [comment]
Fix for enemies getting stuck in the walls/off the screen. Closed by 21b328bf1e4752b3228089f48b674c1d79751212

**Comment by richtaur** [comment]
wooo!!!
