### ISSUE TITLE
Clouds

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#42]
Need to make the game more interesting. Low hanging fruit is have some scrolling clouds overlayed on top of the action!

(Or fog or whatever looks awesome and is easy.)

**Comment by richtaur** [comment]
WIP in DB. They look pretty good at 90% I think.

**Comment by richtaur** [comment]
*90% opacity

**Comment by geoffb** [comment]
90% opacity seems rather high. I'd assume we want the clouds to be nearly transparent so as not to obscure the gameplay.

**Comment by richtaur** [comment]
You're rather high!

**Comment by richtaur** [comment]
Put the clouds in objects sheet, keep them in the 32x32 grid.

**Comment by richtaur** [comment]
Graphics in 712b808.

**Comment by geoffb** [comment]
Clouds yaaaaaaaaay. Closed by aa9952cfa0bfdd2e27a93674b912a53dd89bff5b

**Comment by richtaur** [comment]
Make them more "misty".

**Comment by richtaur** [comment]
Put in something more like the old clouds but with feathered borders.

**Comment by richtaur** [comment]
closed by b42954d0d2f656c3599c5b9dad352ebe1e573f76. now gotta get back to paying the bills ...
