### ISSUE TITLE
New enemy: Flaming Skull

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#46]
Needs graphics.

Should "bounce" around the screen breakout-style leaving a trail of fire.

**Comment by richtaur** [comment]
Graphics in 712b808.

**Comment by geoffb** [comment]
Added flaming skull enemy. Closed by eb53cf73d7eadc37b631db0454dc025aba1869d4

**Comment by richtaur** [comment]
Gonna tighten up the graphics:
- Pain frame is too easy to miss.
- Death animation sucks. Should probably just have the skull fall and maybe crumble.

**Comment by richtaur** [comment]
closed by f23b37fe5c2da341a4812af04e85b441f9ab5576
