### ISSUE TITLE
New enemy: Gelatinous Cube

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#47]
Needs graphics. (+ spawns)

Should wiggle around the screen slowly. Spawns small jelly enemies which are fast and low hit points every time it's wounded. This makes it more effective to use higher damage weapons against it.

It could also have a phase where it stops, shudders and spawns a bunch of jelly enemies.

**Comment by richtaur** [comment]
Cube can only be hurt by fire and his adds will drop fire if you don't have it.

**Comment by richtaur** [comment]
Rotate the skull and knife so they look like they're floating. Also need some basic adds, little slimes.

**Comment by richtaur** [comment]
Try to get in 3 different slimes with varying innards (giblets, etc.)

**Comment by richtaur** [comment]
closed by cf1224db6cba17d4106f4986eb558b2255123bf7 - cube adds
