### ISSUE TITLE
New enemy: Spike Sentry

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#50]
Graphics done.

Sits in the corners and charges the player when he's aligned on the X or Y axis.

Moves back into position once charge is complete.

**Comment by geoffb** [comment]
Spike sentries. Closed by 39d67f559971b6bca16e9a13e317ee37f706b0c7

**Comment by richtaur** [comment]
Make bloody versions to be used after they hit the player. Cool!

**Comment by richtaur** [comment]
Added bloody spikes in 2f3548804bd071e5b8738e7c4aacaae30f9a448a.

**Comment by geoffb** [comment]
Spike sentries get bloody when they damage the player. Closed by 5ad2ff37ca129972cfbfb1c4fdd68a488d12a8ed
