### ISSUE TITLE
Save high score and display to user when new records are set

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#52]
Save high score for the player using local storage. Display new records when achieved. Show current high score on title screen.

**Comment by richtaur** [comment]
Horde.save data / load data. Assigning to Matt.

**Comment by richtaur** [comment]
closed by 05fcee86b2fa8664ae20bee94bff7bf421bca17f

**Comment by richtaur** [comment]
Let's use #53 (Revamp game over screen into stats screen) and #55 (Victory cutscene) for displaying to the user when the high score is beat.
