### ISSUE TITLE
Victory cutscene

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#55]
Hero moves to the center. pumps fist and roses are thrown all over. Victory music plays.

**Comment by geoffb** [comment]
Victory cutscene, finally. Closed by af56e399b8296f53033bc8a7b521db0e49a569ff

**Comment by richtaur** [comment]
Make a "VICTORY!" image and display it if you beat the game instead of "Game Over".

**Comment by richtaur** [comment]
closed by 8fb3826b903961199d2a879f5b1fab77b22a876c
