### ISSUE TITLE
More Gameplay Balancing

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#56]
We need to spend some time balancing the game again after all the new enemies and such are done.

**Comment by richtaur** [comment]
The goal is that neither of us (playing at expert levels) can get past the 5th cycle.

**Comment by geoffb** [comment]
General order of hero weapons by strength:
- Sword
- Knife
- Spear
- Fireball
- Battle Axe
- Flame Sword

**Comment by geoffb** [comment]
Current enemies:
- Bats
- Dire Bats
- Goblins
- Demoblins
- Imps
- Sandworms
- Flaming Skulls
- Cyclops
- Wizards
- Beholder Eyelets
- Gelatinous Cube Gels

**Comment by geoffb** [comment]
Bosses:
- Superclops
- Dragon
- Gelatinous Cube
- Beholder
- Nega Xam??

**Comment by richtaur** [comment]
Notes from today:
- First 20 waves are essentially done (superclops and dragon bosses included)
- Some tweaks probably needed, like wizards might drop too much fire
- New version is 0.4.1

**Comment by richtaur** [comment]
Notes from tonight:
- Lots of little tweaks, like nerfing cyclops, wizard shots are indestructible, rearranged some waves, differing weapon drops.
- Decided on doing "Wave X/Y" between waves and adding a "Continue" option on the title screen.
- etc.!

**Comment by richtaur** [comment]
Things remaining:
- tone the difficulty the fuck down!
- stuff that slows you slows you too much probably
- finish all waves
- tone owl bear
- tone nega xam
- implement beholder

**Comment by richtaur** [comment]
Note: all that's left are waves 41-45!

**Comment by richtaur** [comment]
And waves **35-39** too.

**Comment by geoffb** [comment]
All waves populated.
