### ISSUE TITLE
Wizard tweaks

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#58]
- Improve his hands in the second frame, have them move up/down a bit.
- Make a new weapon for him: a wavy thingy in the same color as his hands.

**Comment by richtaur** [comment]
Graphics in 712b808.

**Comment by geoffb** [comment]
New shock wave attack for wizards. Closed by 1c342fe1da7f976cd6d9ba01167baf1b6ce07731

**Comment by richtaur** [comment]
Added a better projectile for the wizard with a second frame. Can you animate it?

**Comment by geoffb** [comment]
Support for animated projectiles. Closed by 4a92b7baa97765d6863d8f0b91961e91133a85e4
