### ISSUE TITLE
A FRICKIN' BATTLE AXE!!

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#63]
- Konami Code gives you the axe, or:
- It spawns from the Beholder; that's the only way you can get it.
- It rotates and bounces off the damn walls.
- It's totally badass.

**Comment by richtaur** [comment]
- Also should nerf the trident. Focus on making it more fun.

**Comment by richtaur** [comment]
- Fuck it. Fuck the trident. Give it to the demoblins.

**Comment by richtaur** [comment]
Graphics in 712b808.

**Comment by geoffb** [comment]
Batte axe now bounces around. Needs serious balancing, but that will come later. Closed by fef180a7830b4f5496a1e526b324c5483aa0d0fb
