### ISSUE TITLE
Pause messes up the dragon's phase timer

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#66]
When a dragon spawns, if you pause immediately then let it sit for a bit, when you unpause the dragon will immediately charge. So I guess the dragon's timer for what phase he's in doesn't know when the game is paused.

Probably due to my bastardized pause code!

**Comment by geoffb** [comment]
It's actually my bastardized timer code. I thought I would be "smart" and not have to pass the elapsed time to each timer by storing the time when it started. This, however, cannot be paused as it's "real" time and not game time. Doh!

**Comment by geoffb** [comment]
Timer fixes, projectiles don't die if they one shot an enemy. Closed by 9228f8f09e29c4eae34fd26927f44d707b138990
