### ISSUE TITLE
Possible spike issue

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#67]
The upper-right spike disappeared around wave 6-7. I had been hit by it so it was bloody. It would still hit me if I moved into that area, but it wasn't rendering. Then one of the times I let it hit me to test, the screen did that weirdness where it exploded and drew the background at various rotations.

Error was DOM Exception 1 on engine.js:1573.

**Comment by geoffb** [comment]
I suck at programming. Closed by e126ff13219e5b0e0cb5b00fb3eda3b3444af406
