### ISSUE TITLE
New enemy: sandworm

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#69]
First looks like something burrowing underground, then pops out and shoots some shit at the player.

**Comment by richtaur** [comment]
I'm not thrilled with it but I think it's good enough, which is about how I feel about this stuff at this point, heh: https://github.com/lostdecade/onslaught/commit/6f6f32333d93b6d3b44bdeab99fcc92dd07f89b8

**Comment by richtaur** [comment]
Make a purple segmented sandworm. Give him a new projectile (purple goo) which turns into a purple puddle (2 frames, 64x64).

**Comment by richtaur** [comment]
It's all in there, yo. 44ce3a761f40ab4f7c7b80f3a99330d374198ba1

**Comment by richtaur** [comment]
Worms are easy to do if you want another one or just a different one.

**Comment by geoffb** [comment]
Fixed by 9aeb6cd964342b1205aa.

Sandworms now spit crap that forms pools which slow down and damage the player.
