### ISSUE TITLE
New enemy: Beholder gas clouds

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#72]
Gas clouds! Should flow like mist kinda.

**Comment by richtaur** [comment]
Draft here: https://github.com/lostdecade/onslaught/commit/3ba1cd590752932f6e630eafb586f277844506e5 will probably tweak once we see them in action.

**Comment by geoffb** [comment]
Beholder gas clouds. Closed by 5630c24ab974b1a242afec435b7ad27547cacc55
