### ISSUE TITLE
The sounds for food and treasure are very low volume.

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#76]
Can hardly hear them during game play.

**Comment by richtaur** [comment]
closed by 3a9855ecf082a32c36d661a4791b95e45ab74ceb

**Comment by richtaur** [comment]
Wow now it's way too loud.

**Comment by geoffb** [comment]
Lowered volume of food and gold pickups via code. Works for now. Closed by f4f3ec778fd0d4c425e3afe6c2d9e59755643ffe
