### ISSUE TITLE
More of a spread on fireball weapon and dragon fire

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#78]
Right now the fireball weapon and dragon fire both shoot in straight lines. Let's make it more interesting by having them stagger or randomly change a few degrees, more like a shotgun kind of feel.

**Comment by geoffb** [comment]
Hero and dragon fire now shoot 3 at a time in a spread fasion, each modified by a slight amount of randomness. Closed by 9c81344b1bceb6e16cc5ada29a4b1635dc939769
