### ISSUE TITLE
Make spawning animation for spikes

### ISSUE THREAD

**Issue by geoffb** [lostdecade/onslaught_arena#92]
DOIT

**Comment by richtaur** [comment]
In 8a50913057713399eafb54bb66a72f7abb63de60.

**Comment by geoffb** [comment]
Spikes now have spawning animation. Closed by 299b44967ee53c6d52dda54a2b5872050ea02e95

**Comment by richtaur** [comment]
Reopening so we can do the same with the rotating ones. Make them come out of the sand!
