### ISSUE TITLE
Could use another big slow monster

### ISSUE THREAD

**Issue by richtaur** [lostdecade/onslaught_arena#98]
Cyclops is getting overused ATM. How about a bear or a displacer beast? Definitely a nice-to-have.

**Comment by richtaur** [comment]
OWL BEAR! Occasionally charges you at. Would be soooo good.

**Comment by richtaur** [comment]
In e43c61e3d694b92a62638b4c1a1df9671992226a!

**Comment by geoffb** [comment]
We has OWLBEAR: 803078fdd1d65970c47786a7ef277228e8ec9d2c
